Backend state changes
TranscendVR/transcend pull request #47
Opened 2017-02-06 22:34 UTC by Jmikeydarby

I took the socket and room objects out of the backend socket.js and moved them to the backend state and implemented immutable.js on them.

2017-02-06 22:37 UTC, parky22 commented on server/socket.js
>  const { createAndEmitUser, updateUserData, removeUserAndEmit } = require('./redux/reducers/user-reducer');
extra space

2017-02-06 22:37 UTC, parky22 commented on server/socket.js
> +
extra space

2017-02-06 22:41 UTC, Jmikeydarby commented on server/socket.js
> +
separating the reducers from everything else to make it look neater

2017-02-06 22:41 UTC, Jmikeydarby commented on server/socket.js
> +
I can remove if people don't like that

2017-02-06 22:48 UTC, parky22 commented on server/socket.js
> +      const sockets = store.getState().sockets;
why is this not colored like the other variables? like line 114. might not be a big deal but it's bothering me.

2017-02-07 00:42 UTC, Jmikeydarby commented on server/socket.js
> +      const sockets = store.getState().sockets;
because it's highlighted as the start of the diff

2017-02-07 02:25 UTC, spmcbride1201 commented on browser/webRTC/client.js
> +    url: 'turn:192.158.29.39:3478?transport=udp',
pinged all of these just to sanity check that they're live, and they responded as expected.

2017-02-07 02:27 UTC, spmcbride1201 commented on server/redux/reducers/room-reducer.js
> +const REMOVE_SOCKET_TO_ROOM = 'REMOVE_SOCKET_TO_ROOM';
sort of semantically confusing wording. I see you're using removeSocketFromRoom below. Can you change this to match?

2017-02-07 02:59 UTC, bushidocodes requested changes
Bosstastic code. You were like the borg. You descended upon the state hiding throughout the server and assimilated into the great collective of Redux. The only teeny change I request is the semantic change to the action to used `REMOVE_SOCKET_FROM_ROOM`. Thank you for being a great American!

2017-02-07 02:59 UTC, spmcbride1201 commented on server/redux/reducers/room-reducer.js
> +    case REMOVE_SOCKET_TO_ROOM:
save as above

2017-02-07 02:59 UTC, spmcbride1201 commented on browser/webRTC/client.js
> -  { url: 'stun:stun.l.google.com:19302' }
Joey's the #1 Stunna. Wha Wha Wha Wha? https://youtu.be/f56A7obPbtE?t=2m15s

2017-02-07 02:59 UTC, spmcbride1201 commented on server/redux/reducers/room-reducer.js
> +    type: REMOVE_SOCKET_TO_ROOM,
Same as above

2017-02-07 03:44 UTC, bethqiang approved these changes

2017-02-07 03:44 UTC, bethqiang commented on server/socket.js
> +      const sockets = store.getState().sockets;
^lol

2017-02-07 03:44 UTC, bethqiang commented on server/socket.js
> +      store.getState().rooms.get(room).valueSeq().forEach(peer => {
To make this (& line 86) slightly more consumable (???), I'd maybe save part of it as a variable, but I also understand that that variable wouldn't be used anywhere else sooo...

...idk I'm conflicted. Not really asking you to change anything. Just expressing the feelz.

2017-02-07 03:45 UTC, bethqiang commented on server/socket.js
> +      const sockets = store.getState().sockets;
^LOL

2017-02-07 16:43 UTC, merged